# PostgreSQL - Relational Data (Products, Users)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_inventory
spring.datasource.username=joan_admin
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB - Flexible Logs (Stock Movements)
spring.mongodb.uri=mongodb://admin:password123@localhost:27017/smart_inventory?authSource=admin